# Generated by Django 5.2.5 on 2025-08-19 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
